language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: DYuXL+fTc5oibi72BR1k7WZ7Hu07HVM++GoJYEWnEnWqHdHXPRix7gIrRL2bizE88AJ7jFi+Y2pZYECIKX0qEj7KLjHd767RIjjJNaqGKyk5yu5+s0xFHqcF4D+CY/3Qha3O4OtZAV1Om5QI0tb2cH+oBtpTr20Fxfoe+oTCrkthze1yMjXbIj+eElYsk7Mk3qRb4OMsx4riicklPMYpc12KoL7yk/QWRHsv0MyJzszSRoYTCDKW4HAaue3e9qRKab0xRcKR7z3+jfxLcUfyZG8eLK3YFyaQDeMNMWgijnOvdEd5N91N0qHwS43mbP5LlK4tIk76EcsUnhXBxc+HUQus3aln9JB8NwMCUQbzOnQsRc5cxxW5KMJybzBuT7VSS0Z06FnnqJ04cEP70HWgKKkxE4KAx++rpCqYm2VBsKbenR+l84PT9TfUyjYwVKDOCbpQB6F7PFB65aA4UEpfOhyt483aMdAeQ++s0Y2gelGXceB0d6AluhlmX6+9Eb+uCtc33+KL34yLzhDjZ9A4IZ4tqeVNwRbJuKml1X/SBNNqXjSW2hnLrInXLb33FeJHyjaItBadPqSVrwnLMytU39ebYyTwn9r1+9CW398loDLGyPnFKjro+AC6IYBdeuIZLmVppcaL3iadwmYFTinKQlbIt5hBfFeEkW25duEJ04Y=
  app: nameless-ravine-82023
  on:
    repo: jylei/node-shopping-list-integration-test
