language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: UW38fd84Gz10ruw2kJ4XaFqcc+LORqnu7rhC8ikdJO3h9sRizg6pjBPcvHgk4h3VIrjWNbQ1O+194TUkkhYjvAjrBTMlnS06bgjT/AuUgEPB2bloV0AqpZnroGZXCRdHBnyslwrJrjJVe1cXbhcyCt/m5No/iTUfkOLswUZ15R+Vr5AQ5lcVh9iW1AtBnNN/qtIfJcCj0u1hTNIb4YN6QuX/wGPgeWgN2T0srSVOZg0DTFU3pcwOV36VEjSG8iNixFhyqEOFz0a6JEcbIISo9cxD7ELtEavL+pCquKip1l3vDwmeAi7ZEH6eNxjOfjLbJH+ySH2fjpTGHSkeyACgTrfbdv6QGeLmvMY4fty3U++VDRCOo1uWWdgXmj8T779ewiita3omp3Idz/6FIHlr/RtKWM3JwMcCh84+epGn9f0uqBlt+RIbvE8GOMqRy65yM2WV0YsE/l3Eq6UsUakhN3yb5n5I0alR2fsBKSiJ6Xgp7o0rQ43yldR/7vv3lzsJoxE7tNHTZ9tcFNWCwe/rFkuVEV2+LLjm22gJFStB5qqQDlr9j51lLom4YYoj3BLsBnCjziCGBuIQwLfADW4egDhS9/fzYtv0V5wKkM++VZw17Wqe2/UeP0S//djTxTJ3zsqXa2/zOik783d9ZVK/DrYJPDMML3pIhGIrYjQULTc=
  app: node-shopping-list-integration-test
  on:
    repo: jylei/node-shopping-list-integration-test
